spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myproject
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

grpc:
  port: 9090